### ISSUE TITLE
MetaBrainz.MusicBrainz.CoverArt Update

### ISSUE THREAD

**Issue by RolandoKRC** [Zastai/MetaBrainz.MusicBrainz.CoverArt#1]
Good morning, I am using MetaBrainz.MusicBrainz with MetaBrainz.MusicBrainz.CoverArt and I have updated the first one together with its MetaBrainz.Common.Json dependency to the last one released, but at the moment of wanting to instantiate the MetaBrainz.MusicBrainz.CoverArt it gives me an error due to the MetaBrainz.Common.Json update. My question is whether this MetaBrainz.MusicBrainz.CoverArt project will also undergo an update to MetaBrainz.Common.Json as was the case with the MetaBrainz.MusicBrainz project.
Greetings and thank you very much and congratulations on this very useful project.

**Comment by Zastai** [comment]
Released v3.0.0, which uses the same version of `MetaBrainz.Common.Json` as `MetaBrainz.MusicBrainz`.

Note: you're not required to update immediately to every new version that comes out, especially when that causes other dependencies to break.
