### ISSUE TITLE
Why is `ClientLock` used?

### ISSUE THREAD

**Issue by 89netraM** [Zastai/MetaBrainz.MusicBrainz.CoverArt#30]
https://github.com/Zastai/MetaBrainz.MusicBrainz.CoverArt/blob/17d3806240ca3bde3d55158e1d3520160fa12fce/MetaBrainz.MusicBrainz.CoverArt/CoverArt.cs#L552

I am using this library to fetch links to album arts from one artist, doing it in parallel for some speedup. I noticed that the `ClientLock` makes it so that only one fetch request can be done at a time. Why is that? According to the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0#remarks) `SendAssync` on `HttpClient` is thread safe. (And I can't notice anything else that would require the lock.)

**Comment by Zastai** [comment]
This may be a relic from before this switched to `HttpClient`. I'll have to investigate to see if it can be dropped now.

Note that the `CoverArt` class is fairly lightweight, so for now you could just create a new instance for each request (as long as you dispose it).

**Comment by Zastai** [comment]
A simple `Parallel.For(1, 25, ...)` containing 2 release info fetches shows this working perfectly and taking only ~1 second, while with the lock it takes ~35 seconds.
