### ISSUE TITLE
NOOB question

### ISSUE THREAD

**Issue by rbutarascu** [Zastai/MetaBrainz.MusicBrainz.CoverArt#5]
Hello all!

Please forgive me for such a basic question. I downloaded the source code and opened the solution file using VS 2019.
When i tried to build, i got errors stating that Common.targets and Common.props are missing. Indeed, the whole "build" is empty. What am I missing?

Thank you!
RB

**Comment by Zastai** [comment]
`build` is a Git submodule (pointing to [MetaBrainz.Build](https://github.com/Zastai/MetaBrainz.Build)).

If by "downloaded" you mean "cloned the Git repository", you will need to run `git submodule update --init --recursive` to get its contents.

If you downloaded the zip that GitHub provides as part of tagged releases, you'll probably need to get the sources from https://github.com/Zastai/MetaBrainz.Build yourself. But that's not a scenario I provide support for.

**Comment by rbutarascu** [comment]
Thank you for your help, I was able to clone it using GitHub Desktop and got everything needed in one move. Then I was able to build the assembly as well.
